name: wf_call_sf_objects

on:
  push:
    branches:
      - dev
      - qut
      - main
    paths:
      - $TARGET_PATH
  workflow_dispatch:   # Allow manual triggering of the workflow

jobs:
  deploy_dev:
    if: github.ref == 'refs/heads/dev' 
    uses: ./.github/workflows/wf_sf_objects.yml
    with:
      environment: dev
    secrets: inherit

  deploy_qut:
    if: (github.ref == 'refs/heads/main' && github.event.repository.name != 'RepoED') || (github.ref == 'refs/heads/qut' && github.event.repository.name == 'RepoED')
    uses: ./.github/workflows/wf_sf_objects.yml
    with:
      environment: qut
    secrets: inherit

  deploy_prd:
    if: github.ref == 'refs/heads/main' && github.event.repository.name == 'RepoED'
    uses: ./.github/workflows/wf_sf_objects.yml
    with:
      environment: prd
    secrets: inherit
