name: wf_call_sf_objects

on:
  # push:
  #   branches:
  #     - dev
  #     - qut
  #     - main
  workflow_dispatch:   # Allow manual triggering of the workflow

jobs:
  deploy_dev:
    if: github.ref == 'refs/heads/dev' 
    uses: ./.github/workflows/wf_sf_objects.yml
    with:
      environment: dev

  deploy_qut:
    if: (github.ref == 'refs/heads/main' && github.event.repository.name != 'RepoED') || (github.ref == 'refs/heads/qut' && github.event.repository.name == 'RepoED')
    uses: ./.github/workflows/wf_sf_objects.yml
    with:
      environment: qut

  deploy_prd:
    if: github.ref == 'refs/heads/main' && github.event.repository.name == 'RepoED'
    uses: ./.github/workflows/wf_sf_objects.yml
    with:
      environment: prd
