name: wf_sf_scripts

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:          
      - name: Retrieve Repository
        uses: actions/checkout@v3
      - name: Use Python 3.8.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.x
      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.3/linux_x86_64/snowsql-1.3.0-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.3.0-linux_x86_64.bash
      - name: Deploy
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }} 
          SNOWSQL_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          TARGET_TASKID_RANGE: ${{ vars.TARGET_TASKID_RANGE }}
        run: |
          ~/bin/snowsql -f $GITHUB_WORKSPACE/scripts/DDL_MainControlTable.sql
          ~/bin/snowsql -f $GITHUB_WORKSPACE/scripts/DDL_ConnectionControlTable.sql
          if [[ -n $TARGET_TASKID_RANGE ]]; then
              # If this job runs at the project repo
              # Only run the target taskid range subdirectory and skip the other subdirectories
              echo "Target TaskID Range is $TARGET_TASKID_RANGE!"
              for sql_file in $(find "$GITHUB_WORKSPACE/scripts/$TARGET_TASKID_RANGE" -name '*.sql'); do
                  relative_path="${sql_file#$GITHUB_WORKSPACE/}"
                  echo "Processing sql file: $relative_path"
                  ~/bin/snowsql -f "$GITHUB_WORKSPACE/$relative_path"


                  # sql_query=$(cat "$GITHUB_WORKSPACE/$relative_path")
                  
                  # ~/bin/snowsql -q "EXECUTE IMMEDIATE $$ $sql_query $$"  


          
              done
          else
              # If this job runs at the ED repo
              # Loop through all subdirectories for all taskid ranges
              for sql_file in $(find "$GITHUB_WORKSPACE/scripts" -name '*.sql'); do
                  relative_path="${sql_file#$GITHUB_WORKSPACE/}"
                  echo "Processing sql file: $relative_path"
                  ~/bin/snowsql -f "$GITHUB_WORKSPACE/$relative_path"
              done
          fi
